In [1]:
import plotly.graph_objects as go
import numpy as np
from os.path import dirname, join as pjoin
import scipy.io as sio

In [2]:
mat_fname = pjoin('mesh', 'bowtie.mat')
print(mat_fname)
mat_contents = sio.loadmat(mat_fname)

mesh\bowtie.mat


In [13]:
p = mat_contents['p']
x_, y_, z_ = p

fig = go.Figure(data=[go.Mesh3d(x=x_, y=y_, z=z_, color='lightgreen', opacity=0.8)])
fig.update_layout(width=700, margin=dict(r=10, l=10, b=10, t=10))
# fix the ratio in the top left subplot to be a cube
fig.update_layout(scene_aspectmode='manual',
                  scene_aspectratio=dict(x=1, y=1, z=0.5))
fig.show()

In [4]:
max(p[1,:])-min(p[1,:])

0.2

In [5]:
p.shape

(3, 174)

In [6]:
max(p[0,:])-min(p[0,:])

0.198

In [7]:
max(p[2,:])-min(p[2,:])

0.0

In [15]:
y_

array([ 0.1       ,  0.007     , -0.007     , -0.1       , -0.1       ,
       -0.007     ,  0.007     ,  0.1       ,  0.08960066,  0.07946235,
        0.06957851,  0.05994275,  0.05054885,  0.04139074,  0.0324625 ,
        0.02375835,  0.01527268,  0.        , -0.01527268, -0.02375835,
       -0.0324625 , -0.04139074, -0.05054885, -0.05994275, -0.06957851,
       -0.07946235, -0.08960066, -0.1       , -0.1       , -0.1       ,
       -0.1       , -0.1       , -0.1       , -0.1       , -0.1       ,
       -0.1       , -0.1       , -0.1       , -0.1       , -0.1       ,
       -0.08960066, -0.07946235, -0.06957851, -0.05994275, -0.05054885,
       -0.04139074, -0.0324625 , -0.02375835, -0.01527268,  0.        ,
        0.01527268,  0.02375835,  0.0324625 ,  0.04139074,  0.05054885,
        0.05994275,  0.06957851,  0.07946235,  0.08960066,  0.1       ,
        0.1       ,  0.1       ,  0.1       ,  0.1       ,  0.1       ,
        0.1       ,  0.1       ,  0.1       ,  0.1       ,  0.1 

In [16]:
x_

array([-9.90000000e-02, -6.00000000e-03, -6.00000000e-03, -9.90000000e-02,
        9.90000000e-02,  6.00000000e-03,  6.00000000e-03,  9.90000000e-02,
       -8.86006632e-02, -7.84623498e-02, -6.85785082e-02, -5.89427512e-02,
       -4.95488517e-02, -4.03907393e-02, -3.14624955e-02, -2.27583508e-02,
       -1.42726802e-02, -6.00000000e-03, -1.42726802e-02, -2.27583508e-02,
       -3.14624955e-02, -4.03907393e-02, -4.95488517e-02, -5.89427512e-02,
       -6.85785082e-02, -7.84623498e-02, -8.86006632e-02, -8.48571429e-02,
       -7.07142857e-02, -5.65714286e-02, -4.24285714e-02, -2.82857143e-02,
       -1.41428571e-02,  0.00000000e+00,  1.41428571e-02,  2.82857143e-02,
        4.24285714e-02,  5.65714286e-02,  7.07142857e-02,  8.48571429e-02,
        8.86006632e-02,  7.84623498e-02,  6.85785082e-02,  5.89427512e-02,
        4.95488517e-02,  4.03907393e-02,  3.14624955e-02,  2.27583508e-02,
        1.42726802e-02,  6.00000000e-03,  1.42726802e-02,  2.27583508e-02,
        3.14624955e-02,  

In [18]:
z_

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0.])